### ISSUE TITLE
Link to Dataset is broken

### ISSUE THREAD

**Issue by Idontker** [check24-scholarships/check24-best-combination-challenge#1]
Hi there, 

the link within the README.md file leading to the dataset is broken: 
https://github.com/check24-scholarships/check24-best-combination-challenge-datasets

**Comment by justKMM** [comment]
You need to join the challenge first to access the dataset. The link to join the challenge is included in the README.md you mentioned (or: https://check24-6th-gendev.vpetritz.net/)

**Comment by tutNichts** [comment]
Hi!

As mentioned by @justKMM you have to start the challenge by clicking the link at the end of the readme file: "[Click here to start the challenge and access the datasets 🚀](https://check24-6th-gendev.vpetritz.net/)"
