### ISSUE TITLE
Dataset issue

### ISSUE THREAD

**Issue by spKay18** [check24-scholarships/check24-best-combination-challenge#3]
Hi,
I would like to know if the dataset posted in Github is the same dataset used for evaluation of the project.

It makes big difference for storing the data, if the evaluation dataset contains much more data.

**Comment by tutNichts** [comment]
Hi @spKay18 ,

we'll mainly use this dataset. However, your application should be able to handle different datasets that vary not too much in size, but in their actual content.

Good luck! 🚀
